=begin comment

IdCheck.IO API

Check identity documents

OpenAPI spec version: 0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

=end comment

=cut

#
# NOTE: This class is auto generated by Swagger Codegen
# Please update the test cases below to test the API endpoints.
# Ref: https://github.com/swagger-api/swagger-codegen
#
use Test::More tests => 3; #TODO update number of test cases
use Test::Exception;

use lib 'lib';
use strict;
use warnings;

use_ok('IdcheckioPerl::Client::AnalysisApi');
use_ok('IdcheckioPerl::Client::ApiClient');

my $apiClient = IdcheckioPerl::Client::ApiClient->instance(base_url => 'https://api.idcheck.io:443/rest');
my $api = IdcheckioPerl::Client::AnalysisApi->new(api_client => $apiClient);
isa_ok($api, 'IdcheckioPerl::Client::AnalysisApi');

#
# get_report test
#
#{
#    my $analysis_ref_uid = undef; # replace NULL with a proper value
#    my $accept_language = undef; # replace NULL with a proper value
#    my $result = $api->get_report(analysis_ref_uid => $analysis_ref_uid, accept_language => $accept_language);
#}

#
# get_result test
#
#{
#    my $analysis_ref_uid = undef; # replace NULL with a proper value
#    my $accept_language = undef; # replace NULL with a proper value
#    my $recto_image_cropped = undef; # replace NULL with a proper value
#    my $face_image_cropped = undef; # replace NULL with a proper value
#    my $signature_image_cropped = undef; # replace NULL with a proper value
#    my $result = $api->get_result(analysis_ref_uid => $analysis_ref_uid, accept_language => $accept_language, recto_image_cropped => $recto_image_cropped, face_image_cropped => $face_image_cropped, signature_image_cropped => $signature_image_cropped);
#}

#
# get_task test
#
#{
#    my $analysis_ref_uid = undef; # replace NULL with a proper value
#    my $accept_language = undef; # replace NULL with a proper value
#    my $wait = undef; # replace NULL with a proper value
#    my $result = $api->get_task(analysis_ref_uid => $analysis_ref_uid, accept_language => $accept_language, wait => $wait);
#}

#
# post_image test
#
#{
#    my $body = undef; # replace NULL with a proper value
#    my $async_mode = undef; # replace NULL with a proper value
#    my $accept_language = undef; # replace NULL with a proper value
#    my $result = $api->post_image(body => $body, async_mode => $async_mode, accept_language => $accept_language);
#}

#
# post_mrz test
#
#{
#    my $body = undef; # replace NULL with a proper value
#    my $async_mode = undef; # replace NULL with a proper value
#    my $accept_language = undef; # replace NULL with a proper value
#    my $result = $api->post_mrz(body => $body, async_mode => $async_mode, accept_language => $accept_language);
#}


1;
