=begin comment

IdCheck.IO API

Check identity documents

OpenAPI spec version: 0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

=end comment

=cut

#
# NOTE: This class is auto generated by the swagger code generator program. 
# Do not edit the class manually.
# Ref: https://github.com/swagger-api/swagger-codegen
#
package IdcheckioPerl::Client::Object::ImageRequest;

require 5.6.0;
use strict;
use warnings;
use utf8;
use JSON qw(decode_json);
use Data::Dumper;
use Module::Runtime qw(use_module);
use Log::Any qw($log);
use Date::Parse;
use DateTime;

use base ("Class::Accessor", "Class::Data::Inheritable");


#
#
#
# NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
# REF: https://github.com/swagger-api/swagger-codegen
#

=begin comment

IdCheck.IO API

Check identity documents

OpenAPI spec version: 0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

=end comment

=cut

#
# NOTE: This class is auto generated by the swagger code generator program. 
# Do not edit the class manually.
# Ref: https://github.com/swagger-api/swagger-codegen
#
__PACKAGE__->mk_classdata('attribute_map' => {});
__PACKAGE__->mk_classdata('swagger_types' => {});
__PACKAGE__->mk_classdata('method_documentation' => {}); 
__PACKAGE__->mk_classdata('class_documentation' => {});

# new object
sub new { 
    my ($class, %args) = @_; 

	my $self = bless {}, $class;
	
	foreach my $attribute (keys %{$class->attribute_map}) {
		my $args_key = $class->attribute_map->{$attribute};
		$self->$attribute( $args{ $args_key } );
	}
	
	return $self;
}  

# return perl hash
sub to_hash {
    return decode_json(JSON->new->convert_blessed->encode( shift ));
}

# used by JSON for serialization
sub TO_JSON { 
    my $self = shift;
    my $_data = {};
    foreach my $_key (keys %{$self->attribute_map}) {
        if (defined $self->{$_key}) {
            $_data->{$self->attribute_map->{$_key}} = $self->{$_key};
        }
    }
    return $_data;
}

# from Perl hashref
sub from_hash {
    my ($self, $hash) = @_;

    # loop through attributes and use swagger_types to deserialize the data
    while ( my ($_key, $_type) = each %{$self->swagger_types} ) {
    	my $_json_attribute = $self->attribute_map->{$_key}; 
        if ($_type =~ /^array\[/i) { # array
            my $_subclass = substr($_type, 6, -1);
            my @_array = ();
            foreach my $_element (@{$hash->{$_json_attribute}}) {
                push @_array, $self->_deserialize($_subclass, $_element);
            }
            $self->{$_key} = \@_array;
        } elsif (exists $hash->{$_json_attribute}) { #hash(model), primitive, datetime
            $self->{$_key} = $self->_deserialize($_type, $hash->{$_json_attribute});
        } else {
        	$log->debugf("Warning: %s (%s) does not exist in input hash\n", $_key, $_json_attribute);
        }
    }
  
    return $self;
}

# deserialize non-array data
sub _deserialize {
    my ($self, $type, $data) = @_;
    $log->debugf("deserializing %s with %s",Dumper($data), $type);
        
    if ($type eq 'DateTime') {
        return DateTime->from_epoch(epoch => str2time($data));
    } elsif ( grep( /^$type$/, ('int', 'double', 'string', 'boolean'))) {
        return $data;
    } else { # hash(model)
        my $_instance = eval "IdcheckioPerl::Client::Object::$type->new()";
        return $_instance->from_hash($data);
    }
}



__PACKAGE__->class_documentation({description => '',
                                  class => 'ImageRequest',
                                  required => [], # TODO
}                                 );

__PACKAGE__->method_documentation({
    'api_version' => {
    	datatype => 'string',
    	base_name => 'apiVersion',
    	description => 'API version (for backward compatibility purpose)',
    	format => '',
    	read_only => '',
    		},
    'front_image' => {
    	datatype => 'string',
    	base_name => 'frontImage',
    	description => 'frontImage containing front daylight image of the identity document (base64 encoded, no wrap, jpg/png/tiff/pdf format)',
    	format => '',
    	read_only => '',
    		},
    'front_image_ir' => {
    	datatype => 'string',
    	base_name => 'frontImageIr',
    	description => 'frontImage containing front infrared image of the identity document (base64 encoded, no wrap, jpg/png/tiff/pdf format)',
    	format => '',
    	read_only => '',
    		},
    'front_image_uv' => {
    	datatype => 'string',
    	base_name => 'frontImageUv',
    	description => 'frontImage containing front ultraviolet image of the identity document (base64 encoded, no wrap, jpg/png/tiff/pdf format)',
    	format => '',
    	read_only => '',
    		},
    'back_image' => {
    	datatype => 'string',
    	base_name => 'backImage',
    	description => 'backImage containing daylight back image of the identity document (base64 encoded, no wrap, jpg/png/tiff/pdf format)',
    	format => '',
    	read_only => '',
    		},
    'back_image_ir' => {
    	datatype => 'string',
    	base_name => 'backImageIr',
    	description => 'backImage containing infrared back image of the identity document (base64 encoded, no wrap, jpg/png/tiff/pdf format)',
    	format => '',
    	read_only => '',
    		},
    'back_image_uv' => {
    	datatype => 'string',
    	base_name => 'backImageUv',
    	description => 'backImage containing ultraviolet back image of the identity document (base64 encoded, no wrap, jpg/png/tiff/pdf format)',
    	format => '',
    	read_only => '',
    		},
    'recto_image_cropped' => {
    	datatype => 'boolean',
    	base_name => 'rectoImageCropped',
    	description => 'rectoImageCropped true to obtain recto image cropped if applicable',
    	format => '',
    	read_only => '',
    		},
    'face_image_cropped' => {
    	datatype => 'boolean',
    	base_name => 'faceImageCropped',
    	description => 'faceImageCropped true to obtain recto image cropped if applicable',
    	format => '',
    	read_only => '',
    		},
    'signature_image_cropped' => {
    	datatype => 'boolean',
    	base_name => 'signatureImageCropped',
    	description => 'signatureImageCropped true to obtain recto image cropped if applicable',
    	format => '',
    	read_only => '',
    		},
});

__PACKAGE__->swagger_types( {
    'api_version' => 'string',
    'front_image' => 'string',
    'front_image_ir' => 'string',
    'front_image_uv' => 'string',
    'back_image' => 'string',
    'back_image_ir' => 'string',
    'back_image_uv' => 'string',
    'recto_image_cropped' => 'boolean',
    'face_image_cropped' => 'boolean',
    'signature_image_cropped' => 'boolean'
} );

__PACKAGE__->attribute_map( {
    'api_version' => 'apiVersion',
    'front_image' => 'frontImage',
    'front_image_ir' => 'frontImageIr',
    'front_image_uv' => 'frontImageUv',
    'back_image' => 'backImage',
    'back_image_ir' => 'backImageIr',
    'back_image_uv' => 'backImageUv',
    'recto_image_cropped' => 'rectoImageCropped',
    'face_image_cropped' => 'faceImageCropped',
    'signature_image_cropped' => 'signatureImageCropped'
} );

__PACKAGE__->mk_accessors(keys %{__PACKAGE__->attribute_map});


1;
